export const ARTICLE_CONTENT_PROTOCOL_V1 = Object.freeze({
  fileFormat: 'article-content-protocol',
  fileFormatVersion: 1,
  mediaType: 'application/vnd.article-content-protocol+json',
  id: 'article-content-v1',
  version: 1,
  name: 'Article Content Protocol v1',
  status: 'draft',
  rootNode: 'doc',
  nodeTypes: Object.freeze([
    'doc',
    'paragraph',
    'heading',
    'blockquote',
    'bulletList',
    'orderedList',
    'listItem',
    'codeBlock',
    'horizontalRule',
    'image',
    'articleButton',
    'table',
    'tableRow',
    'tableCell',
    'text',
  ]),
  markTypes: Object.freeze(['bold', 'italic', 'strike', 'underline', 'code', 'link']),
})

